"""add campus

Revision ID: 5083e9b50cfb
Revises: d2735bfad5e9
Create Date: 2025-10-08 00:15:14.266128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5083e9b50cfb'
down_revision: Union[str, Sequence[str], None] = 'd2735bfad5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campus_code'), 'campus', ['code'], unique=True)
    op.create_index(op.f('ix_campus_name'), 'campus', ['name'], unique=True)
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('campus_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'campus', ['campus_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'campus_id')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_campus_name'), table_name='campus')
    op.drop_index(op.f('ix_campus_code'), table_name='campus')
    op.drop_table('campus')
    # ### end Alembic commands ###
